//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.1.1+g046e9eb0a2
//       
//       Command:
//           LottieGen -Language CSharp -Public -WinUIVersion 2.4 -InputFile extreme-sleet.json
//       
//       Input file:
//           extreme-sleet.json (24389 bytes created 20:21+05:30 Aug 3 2023)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   252 |
// |--------------------------+-------|
// | Expression animators     |    46 |
// | KeyFrame animators       |    25 |
// | Reference parameters     |    48 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     6 |
// | Animated gradient stops  |    18 |
// | ExpressionAnimations     |    18 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     8 |
// |--------------------------+-------|
// | Brushes                  |    16 |
// | Gradient stops           |    24 |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.Graphics;
using Windows.UI;
using Windows.UI.Composition;

namespace Drizzle.UI.UWP.AnimatedVisuals
{
    // Name:        extreme-sleet
    // Frame rate:  60 fps
    // Frame count: 360
    // Duration:    6000.0 mS
    sealed class SleetExtreme
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
    {
        // Animation duration: 6.000 seconds.
        internal const long c_durationTicks = 60000000;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            if (Extreme_sleet_AnimatedVisual.IsRuntimeCompatible())
            {
                var res = 
                    new Extreme_sleet_AnimatedVisual(
                        compositor
                        );
                    return res;
            }

            return null;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 360d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 360d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Extreme_sleet_AnimatedVisual : Microsoft.UI.Xaml.Controls.IAnimatedVisual
        {
            const long c_durationTicks = 60000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionLinearGradientBrush _linearGradientBrush_2;
            CompositionLinearGradientBrush _linearGradientBrush_3;
            CompositionLinearGradientBrush _linearGradientBrush_4;
            CompositionLinearGradientBrush _linearGradientBrush_5;
            CompositionLinearGradientBrush _linearGradientBrush_6;
            CompositionLinearGradientBrush _linearGradientBrush_7;
            CompositionPathGeometry _pathGeometry_5;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            ExpressionAnimation _colorExpressionAnimation_0;
            ExpressionAnimation _colorExpressionAnimation_1;
            ExpressionAnimation _colorExpressionAnimation_2;
            ExpressionAnimation _rootProgress;
            ExpressionAnimation _rootProgressRemapped_0;
            ExpressionAnimation _rootProgressRemapped_1;
            ScalarKeyFrameAnimation _rotationAngleInDegreesScalarAnimation_0_to_360;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ColorKeyFrameAnimation CreateColorKeyFrameAnimation(float initialProgress, Color initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InterpolationColorSpace = CompositionColorSpace.Rgb;
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            // - - - Layer aggregator
            // - - dark-path
            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(22.8120003F, 8.56200027F));
                    builder.AddCubicBezier(new Vector2(22.8120003F, 26.4769993F), new Vector2(37.3349991F, 41F), new Vector2(55.25F, 41F));
                    builder.AddLine(new Vector2(185F, 41F));
                    builder.AddLine(new Vector2(185F, 40.8829994F));
                    builder.AddCubicBezier(new Vector2(185.768997F, 40.9339981F), new Vector2(186.535004F, 41F), new Vector2(187.317001F, 41F));
                    builder.AddCubicBezier(new Vector2(206.511002F, 41F), new Vector2(222.070999F, 25.4389992F), new Vector2(222.070999F, 6.24499989F));
                    builder.AddCubicBezier(new Vector2(222.070999F, -10.7299995F), new Vector2(209.895004F, -24.8409996F), new Vector2(193.804001F, -27.882F));
                    builder.AddCubicBezier(new Vector2(194.085007F, -29.5979996F), new Vector2(194.268005F, -31.3470001F), new Vector2(194.268005F, -33.1430016F));
                    builder.AddCubicBezier(new Vector2(194.268005F, -51.0579987F), new Vector2(179.744995F, -65.5810013F), new Vector2(161.830002F, -65.5810013F));
                    builder.AddCubicBezier(new Vector2(155.770004F, -65.5810013F), new Vector2(150.119003F, -63.8889999F), new Vector2(145.266006F, -60.9959984F));
                    builder.AddCubicBezier(new Vector2(136.690994F, -74.8539963F), new Vector2(121.399002F, -84.1159973F), new Vector2(103.905998F, -84.1159973F));
                    builder.AddCubicBezier(new Vector2(77.0339966F, -84.1159973F), new Vector2(55.25F, -62.3320007F), new Vector2(55.25F, -35.4599991F));
                    builder.AddCubicBezier(new Vector2(55.25F, -31.434F), new Vector2(55.7929993F, -27.5429993F), new Vector2(56.7150002F, -23.8010006F));
                    builder.AddCubicBezier(new Vector2(56.2260017F, -23.823F), new Vector2(55.7449989F, -23.875F), new Vector2(55.25F, -23.875F));
                    builder.AddCubicBezier(new Vector2(37.3349991F, -23.875F), new Vector2(22.8120003F, -9.35299969F), new Vector2(22.8120003F, 8.56200027F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - black-path
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(116F, -4F));
                    builder.AddCubicBezier(new Vector2(115.146004F, -4F), new Vector2(114.315002F, -3.91100001F), new Vector2(113.471001F, -3.87299991F));
                    builder.AddCubicBezier(new Vector2(115.063004F, -10.3319998F), new Vector2(116F, -17.0489998F), new Vector2(116F, -24F));
                    builder.AddCubicBezier(new Vector2(116F, -70.3919983F), new Vector2(78.3919983F, -108F), new Vector2(32F, -108F));
                    builder.AddCubicBezier(new Vector2(1.79900002F, -108F), new Vector2(-24.6009998F, -92.0090027F), new Vector2(-39.4039993F, -68.0849991F));
                    builder.AddCubicBezier(new Vector2(-47.7820015F, -73.0790024F), new Vector2(-57.5390015F, -76F), new Vector2(-68F, -76F));
                    builder.AddCubicBezier(new Vector2(-98.9280014F, -76F), new Vector2(-124F, -50.9280014F), new Vector2(-124F, -20F));
                    builder.AddCubicBezier(new Vector2(-124F, -16.8999996F), new Vector2(-123.682999F, -13.8800001F), new Vector2(-123.198997F, -10.9169998F));
                    builder.AddCubicBezier(new Vector2(-150.977997F, -5.66699982F), new Vector2(-172F, 18.6940002F), new Vector2(-172F, 48F));
                    builder.AddCubicBezier(new Vector2(-172F, 81.137001F), new Vector2(-145.136993F, 108F), new Vector2(-112F, 108F));
                    builder.AddCubicBezier(new Vector2(-110.649002F, 108F), new Vector2(-109.328003F, 107.886002F), new Vector2(-108F, 107.797997F));
                    builder.AddLine(new Vector2(-108F, 108F));
                    builder.AddLine(new Vector2(116F, 108F));
                    builder.AddCubicBezier(new Vector2(146.927994F, 108F), new Vector2(172F, 82.9280014F), new Vector2(172F, 52F));
                    builder.AddCubicBezier(new Vector2(172F, 21.0720005F), new Vector2(146.927994F, -4F), new Vector2(116F, -4F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - Path 2+Path 1
            // - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_02()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_03(), Geometry_04() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - Layer aggregator
            // - - - Path 2+Path 1
            // - - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-36.4269981F, 107.661003F));
                    builder.AddLine(new Vector2(-42.2080002F, 104.366997F));
                    builder.AddCubicBezier(new Vector2(-41.6889992F, 102.210999F), new Vector2(-41.7140007F, 99.9940033F), new Vector2(-42.2210007F, 97.8909988F));
                    builder.AddLine(new Vector2(-36.4269981F, 94.5889969F));
                    builder.AddCubicBezier(new Vector2(-34.4889984F, 93.4850006F), new Vector2(-33.8240013F, 91.038002F), new Vector2(-34.9440002F, 89.125F));
                    builder.AddCubicBezier(new Vector2(-36.0629997F, 87.2109985F), new Vector2(-38.5369987F, 86.5540009F), new Vector2(-40.4790001F, 87.6610031F));
                    builder.AddLine(new Vector2(-46.2669983F, 90.9599991F));
                    builder.AddCubicBezier(new Vector2(-47.0550003F, 90.2249985F), new Vector2(-47.9290009F, 89.5589981F), new Vector2(-48.9080009F, 89.0009995F));
                    builder.AddCubicBezier(new Vector2(-49.887001F, 88.4430008F), new Vector2(-50.9090004F, 88.0279999F), new Vector2(-51.9480019F, 87.7220001F));
                    builder.AddLine(new Vector2(-51.9480019F, 81.125F));
                    builder.AddCubicBezier(new Vector2(-51.9480019F, 78.9150009F), new Vector2(-53.7610016F, 77.125F), new Vector2(-56F, 77.125F));
                    builder.AddCubicBezier(new Vector2(-58.2389984F, 77.125F), new Vector2(-60.0519981F, 78.9150009F), new Vector2(-60.0519981F, 81.125F));
                    builder.AddLine(new Vector2(-60.0519981F, 87.7289963F));
                    builder.AddCubicBezier(new Vector2(-62.1500015F, 88.3470001F), new Vector2(-64.1080017F, 89.4339981F), new Vector2(-65.7399979F, 90.9560013F));
                    builder.AddLine(new Vector2(-71.5210037F, 87.6610031F));
                    builder.AddCubicBezier(new Vector2(-73.4599991F, 86.5540009F), new Vector2(-75.9369965F, 87.2109985F), new Vector2(-77.0559998F, 89.125F));
                    builder.AddCubicBezier(new Vector2(-78.1760025F, 91.038002F), new Vector2(-77.5110016F, 93.4850006F), new Vector2(-75.572998F, 94.5889969F));
                    builder.AddLine(new Vector2(-69.7919998F, 97.8830032F));
                    builder.AddCubicBezier(new Vector2(-70.310997F, 100.039001F), new Vector2(-70.2860031F, 102.255997F), new Vector2(-69.7789993F, 104.359001F));
                    builder.AddLine(new Vector2(-75.572998F, 107.661003F));
                    builder.AddCubicBezier(new Vector2(-77.5110016F, 108.764999F), new Vector2(-78.1760025F, 111.211998F), new Vector2(-77.0559998F, 113.125F));
                    builder.AddCubicBezier(new Vector2(-76.3050003F, 114.408997F), new Vector2(-74.9440002F, 115.125999F), new Vector2(-73.5429993F, 115.125999F));
                    builder.AddCubicBezier(new Vector2(-72.8560028F, 115.125999F), new Vector2(-72.1589966F, 114.954002F), new Vector2(-71.5210037F, 114.588997F));
                    builder.AddLine(new Vector2(-65.7330017F, 111.290001F));
                    builder.AddCubicBezier(new Vector2(-64.9449997F, 112.025002F), new Vector2(-64.0709991F, 112.691002F), new Vector2(-63.0919991F, 113.249001F));
                    builder.AddCubicBezier(new Vector2(-62.112999F, 113.806999F), new Vector2(-61.0900002F, 114.213997F), new Vector2(-60.0519981F, 114.519997F));
                    builder.AddLine(new Vector2(-60.0519981F, 121.125F));
                    builder.AddCubicBezier(new Vector2(-60.0519981F, 123.334999F), new Vector2(-58.2389984F, 125.125F), new Vector2(-56F, 125.125F));
                    builder.AddCubicBezier(new Vector2(-53.7610016F, 125.125F), new Vector2(-51.9480019F, 123.334999F), new Vector2(-51.9480019F, 121.125F));
                    builder.AddLine(new Vector2(-51.9480019F, 114.511002F));
                    builder.AddCubicBezier(new Vector2(-49.8520012F, 113.892998F), new Vector2(-47.8989983F, 112.808998F), new Vector2(-46.2680016F, 111.289001F));
                    builder.AddLine(new Vector2(-40.4790001F, 114.588997F));
                    builder.AddCubicBezier(new Vector2(-39.8409996F, 114.954002F), new Vector2(-39.144001F, 115.125999F), new Vector2(-38.4570007F, 115.125999F));
                    builder.AddCubicBezier(new Vector2(-37.0559998F, 115.125999F), new Vector2(-35.6949997F, 114.408997F), new Vector2(-34.9440002F, 113.125F));
                    builder.AddCubicBezier(new Vector2(-33.8240013F, 111.211998F), new Vector2(-34.4889984F, 108.764999F), new Vector2(-36.4269981F, 107.661003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - Path 2+Path 1
            // - - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-59.0390015F, 106.321999F));
                    builder.AddCubicBezier(new Vector2(-61.9410019F, 104.667F), new Vector2(-62.9399986F, 100.989998F), new Vector2(-61.2649994F, 98.125F));
                    builder.AddCubicBezier(new Vector2(-60.1399994F, 96.2020035F), new Vector2(-58.0919991F, 95.1259995F), new Vector2(-55.9889984F, 95.1259995F));
                    builder.AddCubicBezier(new Vector2(-54.9589996F, 95.1259995F), new Vector2(-53.9160004F, 95.3850021F), new Vector2(-52.9609985F, 95.9280014F));
                    builder.AddCubicBezier(new Vector2(-50.0589981F, 97.5830002F), new Vector2(-49.0600014F, 101.260002F), new Vector2(-50.7350006F, 104.125F));
                    builder.AddCubicBezier(new Vector2(-52.4119987F, 106.990997F), new Vector2(-56.1339989F, 107.972F), new Vector2(-59.0390015F, 106.321999F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - Path 2+Path 1
            // - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_05()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_06(), Geometry_07() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - Layer aggregator
            // - - - Path 2+Path 1
            // - - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(19.573F, 107.661003F));
                    builder.AddLine(new Vector2(13.7919998F, 104.366997F));
                    builder.AddCubicBezier(new Vector2(14.3109999F, 102.210999F), new Vector2(14.2860003F, 99.9940033F), new Vector2(13.7790003F, 97.8909988F));
                    builder.AddLine(new Vector2(19.573F, 94.5889969F));
                    builder.AddCubicBezier(new Vector2(21.5109997F, 93.4850006F), new Vector2(22.1760006F, 91.038002F), new Vector2(21.0559998F, 89.125F));
                    builder.AddCubicBezier(new Vector2(19.9370003F, 87.2109985F), new Vector2(17.4629993F, 86.5540009F), new Vector2(15.5209999F, 87.6610031F));
                    builder.AddLine(new Vector2(9.7329998F, 90.9599991F));
                    builder.AddCubicBezier(new Vector2(8.94499969F, 90.2249985F), new Vector2(8.0710001F, 89.5589981F), new Vector2(7.09200001F, 89.0009995F));
                    builder.AddCubicBezier(new Vector2(6.11299992F, 88.4430008F), new Vector2(5.09100008F, 88.0279999F), new Vector2(4.05200005F, 87.7220001F));
                    builder.AddLine(new Vector2(4.05200005F, 81.125F));
                    builder.AddCubicBezier(new Vector2(4.05200005F, 78.9150009F), new Vector2(2.23900008F, 77.125F), new Vector2(0F, 77.125F));
                    builder.AddCubicBezier(new Vector2(-2.23900008F, 77.125F), new Vector2(-4.05200005F, 78.9150009F), new Vector2(-4.05200005F, 81.125F));
                    builder.AddLine(new Vector2(-4.05200005F, 87.7289963F));
                    builder.AddCubicBezier(new Vector2(-6.1500001F, 88.3470001F), new Vector2(-8.1079998F, 89.4339981F), new Vector2(-9.73999977F, 90.9560013F));
                    builder.AddLine(new Vector2(-15.5209999F, 87.6610031F));
                    builder.AddCubicBezier(new Vector2(-17.4599991F, 86.5540009F), new Vector2(-19.9370003F, 87.2109985F), new Vector2(-21.0559998F, 89.125F));
                    builder.AddCubicBezier(new Vector2(-22.1760006F, 91.038002F), new Vector2(-21.5109997F, 93.4850006F), new Vector2(-19.573F, 94.5889969F));
                    builder.AddLine(new Vector2(-13.7919998F, 97.8830032F));
                    builder.AddCubicBezier(new Vector2(-14.3109999F, 100.039001F), new Vector2(-14.2860003F, 102.255997F), new Vector2(-13.7790003F, 104.359001F));
                    builder.AddLine(new Vector2(-19.573F, 107.661003F));
                    builder.AddCubicBezier(new Vector2(-21.5109997F, 108.764999F), new Vector2(-22.1760006F, 111.211998F), new Vector2(-21.0559998F, 113.125F));
                    builder.AddCubicBezier(new Vector2(-20.3050003F, 114.408997F), new Vector2(-18.9440002F, 115.125999F), new Vector2(-17.5429993F, 115.125999F));
                    builder.AddCubicBezier(new Vector2(-16.8560009F, 115.125999F), new Vector2(-16.1590004F, 114.954002F), new Vector2(-15.5209999F, 114.588997F));
                    builder.AddLine(new Vector2(-9.7329998F, 111.290001F));
                    builder.AddCubicBezier(new Vector2(-8.94499969F, 112.025002F), new Vector2(-8.0710001F, 112.691002F), new Vector2(-7.09200001F, 113.249001F));
                    builder.AddCubicBezier(new Vector2(-6.11299992F, 113.806999F), new Vector2(-5.09000015F, 114.213997F), new Vector2(-4.05200005F, 114.519997F));
                    builder.AddLine(new Vector2(-4.05200005F, 121.125F));
                    builder.AddCubicBezier(new Vector2(-4.05200005F, 123.334999F), new Vector2(-2.23900008F, 125.125F), new Vector2(0F, 125.125F));
                    builder.AddCubicBezier(new Vector2(2.23900008F, 125.125F), new Vector2(4.05200005F, 123.334999F), new Vector2(4.05200005F, 121.125F));
                    builder.AddLine(new Vector2(4.05200005F, 114.511002F));
                    builder.AddCubicBezier(new Vector2(6.14799976F, 113.892998F), new Vector2(8.10099983F, 112.808998F), new Vector2(9.73200035F, 111.289001F));
                    builder.AddLine(new Vector2(15.5209999F, 114.588997F));
                    builder.AddCubicBezier(new Vector2(16.1590004F, 114.954002F), new Vector2(16.8560009F, 115.125999F), new Vector2(17.5429993F, 115.125999F));
                    builder.AddCubicBezier(new Vector2(18.9440002F, 115.125999F), new Vector2(20.3050003F, 114.408997F), new Vector2(21.0559998F, 113.125F));
                    builder.AddCubicBezier(new Vector2(22.1760006F, 111.211998F), new Vector2(21.5109997F, 108.764999F), new Vector2(19.573F, 107.661003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - Path 2+Path 1
            // - - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-3.03900003F, 106.321999F));
                    builder.AddCubicBezier(new Vector2(-5.94099998F, 104.667F), new Vector2(-6.94000006F, 100.989998F), new Vector2(-5.26499987F, 98.125F));
                    builder.AddCubicBezier(new Vector2(-4.13999987F, 96.2020035F), new Vector2(-2.09200001F, 95.1259995F), new Vector2(0.0109999999F, 95.1259995F));
                    builder.AddCubicBezier(new Vector2(1.04100001F, 95.1259995F), new Vector2(2.08400011F, 95.3850021F), new Vector2(3.03900003F, 95.9280014F));
                    builder.AddCubicBezier(new Vector2(5.94099998F, 97.5830002F), new Vector2(6.94000006F, 101.260002F), new Vector2(5.26499987F, 104.125F));
                    builder.AddCubicBezier(new Vector2(3.58800006F, 106.990997F), new Vector2(-0.134000003F, 107.972F), new Vector2(-3.03900003F, 106.321999F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - Path 2+Path 1
            // - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_08()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_09(), Geometry_10() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - Layer aggregator
            // - - - Path 2+Path 1
            // - - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(75.572998F, 107.661003F));
                    builder.AddLine(new Vector2(69.7919998F, 104.366997F));
                    builder.AddCubicBezier(new Vector2(70.310997F, 102.210999F), new Vector2(70.2860031F, 99.9940033F), new Vector2(69.7789993F, 97.8909988F));
                    builder.AddLine(new Vector2(75.572998F, 94.5889969F));
                    builder.AddCubicBezier(new Vector2(77.5110016F, 93.4850006F), new Vector2(78.1760025F, 91.038002F), new Vector2(77.0559998F, 89.125F));
                    builder.AddCubicBezier(new Vector2(75.9369965F, 87.2109985F), new Vector2(73.4629974F, 86.5540009F), new Vector2(71.5210037F, 87.6610031F));
                    builder.AddLine(new Vector2(65.7330017F, 90.9599991F));
                    builder.AddCubicBezier(new Vector2(64.9449997F, 90.2249985F), new Vector2(64.0709991F, 89.5589981F), new Vector2(63.0919991F, 89.0009995F));
                    builder.AddCubicBezier(new Vector2(62.112999F, 88.4430008F), new Vector2(61.0909996F, 88.0279999F), new Vector2(60.0519981F, 87.7220001F));
                    builder.AddLine(new Vector2(60.0519981F, 81.125F));
                    builder.AddCubicBezier(new Vector2(60.0519981F, 78.9150009F), new Vector2(58.2389984F, 77.125F), new Vector2(56F, 77.125F));
                    builder.AddCubicBezier(new Vector2(53.7610016F, 77.125F), new Vector2(51.9480019F, 78.9150009F), new Vector2(51.9480019F, 81.125F));
                    builder.AddLine(new Vector2(51.9480019F, 87.7289963F));
                    builder.AddCubicBezier(new Vector2(49.8499985F, 88.3470001F), new Vector2(47.8919983F, 89.4339981F), new Vector2(46.2599983F, 90.9560013F));
                    builder.AddLine(new Vector2(40.4790001F, 87.6610031F));
                    builder.AddCubicBezier(new Vector2(38.5400009F, 86.5540009F), new Vector2(36.0629997F, 87.2109985F), new Vector2(34.9440002F, 89.125F));
                    builder.AddCubicBezier(new Vector2(33.8240013F, 91.038002F), new Vector2(34.4889984F, 93.4850006F), new Vector2(36.4269981F, 94.5889969F));
                    builder.AddLine(new Vector2(42.2080002F, 97.8830032F));
                    builder.AddCubicBezier(new Vector2(41.6889992F, 100.039001F), new Vector2(41.7140007F, 102.255997F), new Vector2(42.2210007F, 104.359001F));
                    builder.AddLine(new Vector2(36.4269981F, 107.661003F));
                    builder.AddCubicBezier(new Vector2(34.4889984F, 108.764999F), new Vector2(33.8240013F, 111.211998F), new Vector2(34.9440002F, 113.125F));
                    builder.AddCubicBezier(new Vector2(35.6949997F, 114.408997F), new Vector2(37.0559998F, 115.125999F), new Vector2(38.4570007F, 115.125999F));
                    builder.AddCubicBezier(new Vector2(39.144001F, 115.125999F), new Vector2(39.8409996F, 114.954002F), new Vector2(40.4790001F, 114.588997F));
                    builder.AddLine(new Vector2(46.2669983F, 111.290001F));
                    builder.AddCubicBezier(new Vector2(47.0550003F, 112.025002F), new Vector2(47.9290009F, 112.691002F), new Vector2(48.9080009F, 113.249001F));
                    builder.AddCubicBezier(new Vector2(49.887001F, 113.806999F), new Vector2(50.9099998F, 114.213997F), new Vector2(51.9480019F, 114.519997F));
                    builder.AddLine(new Vector2(51.9480019F, 121.125F));
                    builder.AddCubicBezier(new Vector2(51.9480019F, 123.334999F), new Vector2(53.7610016F, 125.125F), new Vector2(56F, 125.125F));
                    builder.AddCubicBezier(new Vector2(58.2389984F, 125.125F), new Vector2(60.0519981F, 123.334999F), new Vector2(60.0519981F, 121.125F));
                    builder.AddLine(new Vector2(60.0519981F, 114.511002F));
                    builder.AddCubicBezier(new Vector2(62.1479988F, 113.892998F), new Vector2(64.1009979F, 112.808998F), new Vector2(65.7320023F, 111.289001F));
                    builder.AddLine(new Vector2(71.5210037F, 114.588997F));
                    builder.AddCubicBezier(new Vector2(72.1589966F, 114.954002F), new Vector2(72.8560028F, 115.125999F), new Vector2(73.5429993F, 115.125999F));
                    builder.AddCubicBezier(new Vector2(74.9440002F, 115.125999F), new Vector2(76.3050003F, 114.408997F), new Vector2(77.0559998F, 113.125F));
                    builder.AddCubicBezier(new Vector2(78.1760025F, 111.211998F), new Vector2(77.5110016F, 108.764999F), new Vector2(75.572998F, 107.661003F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - - Path 2+Path 1
            // - - Path 2+Path 1.PathGeometry
            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(52.9609985F, 106.321999F));
                    builder.AddCubicBezier(new Vector2(50.0589981F, 104.667F), new Vector2(49.0600014F, 100.989998F), new Vector2(50.7350006F, 98.125F));
                    builder.AddCubicBezier(new Vector2(51.8600006F, 96.2020035F), new Vector2(53.9080009F, 95.1259995F), new Vector2(56.0110016F, 95.1259995F));
                    builder.AddCubicBezier(new Vector2(57.0410004F, 95.1259995F), new Vector2(58.0839996F, 95.3850021F), new Vector2(59.0390015F, 95.9280014F));
                    builder.AddCubicBezier(new Vector2(61.9410019F, 97.5830002F), new Vector2(62.9399986F, 101.260002F), new Vector2(61.2649994F, 104.125F));
                    builder.AddCubicBezier(new Vector2(59.5880013F, 106.990997F), new Vector2(55.8660011F, 107.972F), new Vector2(52.9609985F, 106.321999F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 14F));
                    builder.AddCubicBezier(new Vector2(-4.41800022F, 14F), new Vector2(-8F, 10.4219999F), new Vector2(-8F, 6F));
                    builder.AddLine(new Vector2(-8F, -6F));
                    builder.AddCubicBezier(new Vector2(-8F, -10.4219999F), new Vector2(-4.41800022F, -14F), new Vector2(0F, -14F));
                    builder.AddCubicBezier(new Vector2(4.41800022F, -14F), new Vector2(8F, -10.4219999F), new Vector2(8F, -6F));
                    builder.AddLine(new Vector2(8F, 6F));
                    builder.AddCubicBezier(new Vector2(8F, 10.4219999F), new Vector2(4.41800022F, 14F), new Vector2(0F, 14F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostSkyBlue_FF86C3DB_to_AlmostSkyBlue_FF86C3DB()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 30.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.0833333358F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 40.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.111111112F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 100.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.277777791F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 110.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.305555552F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 210.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.583333313F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 220.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.611111104F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 280.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.777777791F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 290.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.805555582F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Color
            ColorKeyFrameAnimation ColorAnimation_SemiTransparentAlmostRoyalBlue_710A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x71, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 18.95.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.0526315793F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 75.79.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.210526317F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 90.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.25F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 132.63.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.368421048F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 189.47.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.526315808F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 203.68.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.565789461F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 246.32.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.684210539F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 303.16.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.842105269F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 317.37.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.881578922F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 340.11.
                // SemiTransparentAlmostRoyalBlue_770A5AD4
                result.InsertKeyFrame(0.944736838F, Color.FromArgb(0x77, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 360.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(1F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_0()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _holdThenStepEasingFunction);
                // Frame 15.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.0416666679F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 60.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.166666672F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 120.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.333333343F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 135.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.375F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 180.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.5F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 240.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.666666687F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 255.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.708333313F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 300.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.833333313F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_1()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _stepThenHoldEasingFunction);
                // Frame 40.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.111111112F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _holdThenStepEasingFunction);
                // Frame 55.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.152777776F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 100.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.277777791F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 160.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.444444448F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 175.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.486111104F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 220.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.611111104F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 280.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.777777791F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 295.
                // AlmostRoyalBlue_FF0A5AD4
                result.InsertKeyFrame(0.819444418F, Color.FromArgb(0xFF, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                // Frame 340.
                // TransparentAlmostRoyalBlue_000A5AD4
                result.InsertKeyFrame(0.944444418F, Color.FromArgb(0x00, 0x0A, 0x5A, 0xD4), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_0()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _holdThenStepEasingFunction);
                // Frame 10.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.027777778F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 110.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.305555552F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 120.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.333333343F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 180.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.5F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 190.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.527777791F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 290.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.805555582F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 300.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.833333313F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_1()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _stepThenHoldEasingFunction);
                // Frame 50.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.138888896F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _holdThenStepEasingFunction);
                // Frame 60.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.166666672F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 160.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.444444448F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 170.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.472222209F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 230.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.638888896F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 240.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.666666687F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 340.
                // AlmostSkyBlue_FF86C3DB
                result.InsertKeyFrame(0.944444418F, Color.FromArgb(0xFF, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                // Frame 350.
                // TransparentAlmostSkyBlue_0086C3DB
                result.InsertKeyFrame(0.972222209F, Color.FromArgb(0x00, 0x86, 0xC3, 0xDB), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            CompositionColorBrush AnimatedColorBrush_AlmostSkyBlue_FF86C3DB_to_AlmostSkyBlue_FF86C3DB()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_AlmostSkyBlue_FF86C3DB_to_AlmostSkyBlue_FF86C3DB(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionColorBrush AnimatedColorBrush_SemiTransparentAlmostRoyalBlue_710A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_SemiTransparentAlmostRoyalBlue_710A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4(), _rootProgressRemapped_1);
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_0()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_0(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_1()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_1(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_0()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_0(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_1()
            {
                var result = _c.CreateColorBrush();
                StartProgressBoundAnimation(result, "Color", ColorAnimation_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_1(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // black-path
            CompositionColorBrush ColorBrush_AlmostDimGray_FF5B6472()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x5B, 0x64, 0x72));
            }

            // - Layer aggregator
            // dark-path
            CompositionColorBrush ColorBrush_AlmostLightSlateGray_FF848B98()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x84, 0x8B, 0x98));
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_0()
            {
                var result = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                result.StartAnimation("Color", ColorExpressionAnimation_0());
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_1()
            {
                var result = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                result.StartAnimation("Color", ColorExpressionAnimation_1());
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_2()
            {
                var result = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                result.StartAnimation("Color", ColorExpressionAnimation_2());
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_3()
            {
                var result = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,10,100,236)", "my", _linearGradientBrush_5);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_4()
            {
                var result = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,10,100,236)", "my", _linearGradientBrush_6);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_5()
            {
                var result = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,10,100,236)", "my", _linearGradientBrush_7);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0p45_0()
            {
                var result = _c.CreateColorGradientStop(0.449999988F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                result.StartAnimation("Color", _colorExpressionAnimation_0);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0p45_1()
            {
                var result = _c.CreateColorGradientStop(0.449999988F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                result.StartAnimation("Color", _colorExpressionAnimation_1);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0p45_2()
            {
                var result = _c.CreateColorGradientStop(0.449999988F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                result.StartAnimation("Color", _colorExpressionAnimation_2);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0p45_3()
            {
                var result = _c.CreateColorGradientStop(0.449999988F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,9,90,211)", "my", _linearGradientBrush_5);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0p45_4()
            {
                var result = _c.CreateColorGradientStop(0.449999988F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,9,90,211)", "my", _linearGradientBrush_6);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0p45_5()
            {
                var result = _c.CreateColorGradientStop(0.449999988F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,9,90,211)", "my", _linearGradientBrush_7);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_1_0()
            {
                var result = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,94,174,207)", "my", _linearGradientBrush_2);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_1_1()
            {
                var result = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,94,174,207)", "my", _linearGradientBrush_3);
                return result;
            }

            // - - Layer aggregator
            // - Path 2+Path 1
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_1_2()
            {
                var result = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,94,174,207)", "my", _linearGradientBrush_4);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_1_3()
            {
                var result = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,8,80,187)", "my", _linearGradientBrush_5);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_1_4()
            {
                var result = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,8,80,187)", "my", _linearGradientBrush_6);
                return result;
            }

            // - - Layer aggregator
            // - Path 1
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_1_5()
            {
                var result = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(result, "Color", "ColorRGB(my.Opacity0,8,80,187)", "my", _linearGradientBrush_7);
                return result;
            }

            // - - Layer aggregator
            // - dark-path
            // Stop 0
            CompositionColorGradientStop GradientStop_0_AlmostDarkGray_FF9CA2AE()
            {
                return _c.CreateColorGradientStop(0F, Color.FromArgb(0xFF, 0x9C, 0xA2, 0xAE));
            }

            // - - Layer aggregator
            // - black-path
            // Stop 0
            CompositionColorGradientStop GradientStop_0_AlmostSlateGray_FF6B7180()
            {
                return _c.CreateColorGradientStop(0F, Color.FromArgb(0xFF, 0x6B, 0x71, 0x80));
            }

            // - - Layer aggregator
            // - dark-path
            // Stop 1
            CompositionColorGradientStop GradientStop_0p45_AlmostDarkGray_FF9CA2AE()
            {
                return _c.CreateColorGradientStop(0.449999988F, Color.FromArgb(0xFF, 0x9C, 0xA2, 0xAE));
            }

            // - - Layer aggregator
            // - black-path
            // Stop 1
            CompositionColorGradientStop GradientStop_0p447_AlmostSlateGray_FF6B7180()
            {
                return _c.CreateColorGradientStop(0.446999997F, Color.FromArgb(0xFF, 0x6B, 0x71, 0x80));
            }

            // - - Layer aggregator
            // - black-path
            // Stop 2
            CompositionColorGradientStop GradientStop_1_AlmostDarkSlateGray_FF4A5462()
            {
                return _c.CreateColorGradientStop(1F, Color.FromArgb(0xFF, 0x4A, 0x54, 0x62));
            }

            // - - Layer aggregator
            // - dark-path
            // Stop 2
            CompositionColorGradientStop GradientStop_1_AlmostSlateGray_FF6B7180()
            {
                return _c.CreateColorGradientStop(1F, Color.FromArgb(0xFF, 0x6B, 0x71, 0x80));
            }

            // - Layer aggregator
            // dark-path
            CompositionLinearGradientBrush LinearGradientBrush_0()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_AlmostDarkGray_FF9CA2AE());
                colorStops.Add(GradientStop_0p45_AlmostDarkGray_FF9CA2AE());
                colorStops.Add(GradientStop_1_AlmostSlateGray_FF6B7180());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(75F, -75F);
                result.EndPoint = new Vector2(155.623993F, 64.6449966F);
                return result;
            }

            // - Layer aggregator
            // black-path
            CompositionLinearGradientBrush LinearGradientBrush_1()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(GradientStop_0_AlmostSlateGray_FF6B7180());
                colorStops.Add(GradientStop_0p447_AlmostSlateGray_FF6B7180());
                colorStops.Add(GradientStop_1_AlmostDarkSlateGray_FF4A5462());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(-76F, -81F);
                result.EndPoint = new Vector2(57.1860008F, 149.684998F);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            CompositionLinearGradientBrush LinearGradientBrush_2()
            {
                var result = _linearGradientBrush_2 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_0());
                colorStops.Add(AnimatedGradientStop_0p45_0());
                colorStops.Add(AnimatedGradientStop_1_0());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(-66.5169983F, 83.1289978F);
                result.EndPoint = new Vector2(-45.0690002F, 120.278F);
                StartProgressBoundAnimation(result.Properties, "Opacity0", Opacity0ScalarAnimation_0_to_0_0(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            CompositionLinearGradientBrush LinearGradientBrush_3()
            {
                var result = _linearGradientBrush_3 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 255F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_1());
                colorStops.Add(AnimatedGradientStop_0p45_1());
                colorStops.Add(AnimatedGradientStop_1_1());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(-10.5170002F, 83.1289978F);
                result.EndPoint = new Vector2(10.9309998F, 120.278F);
                StartProgressBoundAnimation(result.Properties, "Opacity0", Opacity0ScalarAnimation_255_to_255(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            CompositionLinearGradientBrush LinearGradientBrush_4()
            {
                var result = _linearGradientBrush_4 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_2());
                colorStops.Add(AnimatedGradientStop_0p45_2());
                colorStops.Add(AnimatedGradientStop_1_2());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(45.4830017F, 83.1289978F);
                result.EndPoint = new Vector2(66.9309998F, 120.278F);
                StartProgressBoundAnimation(result.Properties, "Opacity0", Opacity0ScalarAnimation_0_to_0_1(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionLinearGradientBrush LinearGradientBrush_5()
            {
                var result = _linearGradientBrush_5 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_3());
                colorStops.Add(AnimatedGradientStop_0p45_3());
                colorStops.Add(AnimatedGradientStop_1_3());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(508.938995F, -983.218018F);
                result.EndPoint = new Vector2(522.137024F, -960.357971F);
                StartProgressBoundAnimation(result.Properties, "Opacity0", Opacity0ScalarAnimation_0_to_0_2(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionLinearGradientBrush LinearGradientBrush_6()
            {
                var result = _linearGradientBrush_6 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 113.332199F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_4());
                colorStops.Add(AnimatedGradientStop_0p45_4());
                colorStops.Add(AnimatedGradientStop_1_4());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(509.359009F, -974.171997F);
                result.EndPoint = new Vector2(522.557007F, -951.312012F);
                StartProgressBoundAnimation(result.Properties, "Opacity0", Opacity0ScalarAnimation_113p332_to_0(), RootProgressRemapped_1());
                return result;
            }

            // - Layer aggregator
            // Path 1
            CompositionLinearGradientBrush LinearGradientBrush_7()
            {
                var result = _linearGradientBrush_7 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_5());
                colorStops.Add(AnimatedGradientStop_0p45_5());
                colorStops.Add(AnimatedGradientStop_1_5());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(509.779999F, -965.125977F);
                result.EndPoint = new Vector2(522.978027F, -942.267029F);
                StartProgressBoundAnimation(result.Properties, "Opacity0", Opacity0ScalarAnimation_0_to_0_3(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // dark-path
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
            }

            // - Layer aggregator
            // black-path
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_01()));
            }

            // - Layer aggregator
            // Path 2+Path 1
            // Path 2+Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_02()));
            }

            // - Layer aggregator
            // Path 2+Path 1
            // Path 2+Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_3()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_05()));
            }

            // - Layer aggregator
            // Path 2+Path 1
            // Path 2+Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_4()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_08()));
            }

            CompositionPathGeometry PathGeometry_5()
            {
                return _pathGeometry_5 = _c.CreatePathGeometry(new CompositionPath(Geometry_11()));
            }

            // Layer aggregator
            // dark-path
            CompositionSpriteShape SpriteShape_0()
            {
                var result = _c.CreateSpriteShape(PathGeometry_0());
                result.FillBrush = LinearGradientBrush_0();
                result.StrokeBrush = ColorBrush_AlmostLightSlateGray_FF848B98();
                result.StrokeMiterLimit = 5F;
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_0(), RootProgress());
                return result;
            }

            // Layer aggregator
            // black-path
            CompositionSpriteShape SpriteShape_1()
            {
                var result = _c.CreateSpriteShape(PathGeometry_1());
                result.FillBrush = LinearGradientBrush_1();
                result.StrokeBrush = ColorBrush_AlmostDimGray_FF5B6472();
                result.StrokeMiterLimit = 5F;
                result.StrokeThickness = 6F;
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_1(), _rootProgress);
                return result;
            }

            // Layer aggregator
            // Path 2+Path 1
            CompositionSpriteShape SpriteShape_2()
            {
                var result = _c.CreateSpriteShape(PathGeometry_2());
                result.CenterPoint = new Vector2(-55F, 100F);
                result.FillBrush = LinearGradientBrush_2();
                result.StrokeBrush = AnimatedColorBrush_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_0();
                result.StrokeMiterLimit = 5F;
                StartProgressBoundAnimation(result, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_360(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_2(), _rootProgress);
                return result;
            }

            // Layer aggregator
            // Path 2+Path 1
            CompositionSpriteShape SpriteShape_3()
            {
                var result = _c.CreateSpriteShape(PathGeometry_3());
                result.CenterPoint = new Vector2(0F, 100F);
                result.FillBrush = LinearGradientBrush_3();
                result.StrokeBrush = AnimatedColorBrush_AlmostSkyBlue_FF86C3DB_to_AlmostSkyBlue_FF86C3DB();
                result.StrokeMiterLimit = 5F;
                StartProgressBoundAnimation(result, "RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_m360(), _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_3(), RootProgressRemapped_0());
                return result;
            }

            // Layer aggregator
            // Path 2+Path 1
            CompositionSpriteShape SpriteShape_4()
            {
                var result = _c.CreateSpriteShape(PathGeometry_4());
                result.CenterPoint = new Vector2(55F, 100F);
                result.FillBrush = LinearGradientBrush_4();
                result.StrokeBrush = AnimatedColorBrush_TransparentAlmostSkyBlue_0086C3DB_to_TransparentAlmostSkyBlue_0086C3DB_1();
                result.StrokeMiterLimit = 5F;
                StartProgressBoundAnimation(result, "RotationAngleInDegrees", _rotationAngleInDegreesScalarAnimation_0_to_360, _rootProgress);
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_4(), _rootProgress);
                return result;
            }

            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_5()
            {
                var result = _c.CreateSpriteShape(PathGeometry_5());
                result.FillBrush = LinearGradientBrush_5();
                result.StrokeBrush = AnimatedColorBrush_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_0();
                result.StrokeMiterLimit = 5F;
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_5(), _rootProgress);
                return result;
            }

            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_6()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_5);
                result.FillBrush = LinearGradientBrush_6();
                result.StrokeBrush = AnimatedColorBrush_SemiTransparentAlmostRoyalBlue_710A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4();
                result.StrokeMiterLimit = 5F;
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_6(), _rootProgressRemapped_1);
                return result;
            }

            // Layer aggregator
            // Path 1
            CompositionSpriteShape SpriteShape_7()
            {
                var result = _c.CreateSpriteShape(_pathGeometry_5);
                result.FillBrush = LinearGradientBrush_7();
                result.StrokeBrush = AnimatedColorBrush_TransparentAlmostRoyalBlue_000A5AD4_to_TransparentAlmostRoyalBlue_000A5AD4_1();
                result.StrokeMiterLimit = 5F;
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation_7(), _rootProgress);
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                propertySet.InsertScalar("t0", 0F);
                propertySet.InsertScalar("t1", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                StartProgressBoundAnimation(result.Properties, "t0", t0ScalarAnimation_0_to_1(), _rootProgress);
                StartProgressBoundAnimation(result.Properties, "t1", t1ScalarAnimation_0_to_1(), _rootProgressRemapped_0);
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            ExpressionAnimation ColorExpressionAnimation_0()
            {
                var result = _colorExpressionAnimation_0 = _c.CreateExpressionAnimation("ColorRGB(my.Opacity0,133,195,219)");
                result.SetReferenceParameter("my", _linearGradientBrush_2.Properties);
                return result;
            }

            ExpressionAnimation ColorExpressionAnimation_1()
            {
                var result = _colorExpressionAnimation_1 = _c.CreateExpressionAnimation("ColorRGB(my.Opacity0,133,195,219)");
                result.SetReferenceParameter("my", _linearGradientBrush_3.Properties);
                return result;
            }

            ExpressionAnimation ColorExpressionAnimation_2()
            {
                var result = _colorExpressionAnimation_2 = _c.CreateExpressionAnimation("ColorRGB(my.Opacity0,133,195,219)");
                result.SetReferenceParameter("my", _linearGradientBrush_4.Properties);
                return result;
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            ExpressionAnimation RootProgressRemapped_0()
            {
                var result = _rootProgressRemapped_0 = _c.CreateExpressionAnimation("_.Progress*0.9");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            ExpressionAnimation RootProgressRemapped_1()
            {
                var result = _rootProgressRemapped_1 = _c.CreateExpressionAnimation("_.Progress*0.9473684");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_0_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _holdThenStepEasingFunction);
                // Frame 10.
                result.InsertKeyFrame(0.027777778F, 255F, _cubicBezierEasingFunction_0);
                // Frame 110.
                result.InsertKeyFrame(0.305555552F, 255F, _cubicBezierEasingFunction_0);
                // Frame 120.
                result.InsertKeyFrame(0.333333343F, 0F, _cubicBezierEasingFunction_0);
                // Frame 180.
                result.InsertKeyFrame(0.5F, 0F, _cubicBezierEasingFunction_0);
                // Frame 190.
                result.InsertKeyFrame(0.527777791F, 255F, _cubicBezierEasingFunction_0);
                // Frame 290.
                result.InsertKeyFrame(0.805555582F, 255F, _cubicBezierEasingFunction_0);
                // Frame 300.
                result.InsertKeyFrame(0.833333313F, 0F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_0_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _stepThenHoldEasingFunction);
                // Frame 50.
                result.InsertKeyFrame(0.138888896F, 0F, _holdThenStepEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.166666672F, 255F, _cubicBezierEasingFunction_0);
                // Frame 160.
                result.InsertKeyFrame(0.444444448F, 255F, _cubicBezierEasingFunction_0);
                // Frame 170.
                result.InsertKeyFrame(0.472222209F, 0F, _cubicBezierEasingFunction_0);
                // Frame 230.
                result.InsertKeyFrame(0.638888896F, 0F, _cubicBezierEasingFunction_0);
                // Frame 240.
                result.InsertKeyFrame(0.666666687F, 255F, _cubicBezierEasingFunction_0);
                // Frame 340.
                result.InsertKeyFrame(0.944444418F, 255F, _cubicBezierEasingFunction_0);
                // Frame 350.
                result.InsertKeyFrame(0.972222209F, 0F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_0_2()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _holdThenStepEasingFunction);
                // Frame 15.
                result.InsertKeyFrame(0.0416666679F, 255F, _cubicBezierEasingFunction_0);
                // Frame 60.
                result.InsertKeyFrame(0.166666672F, 0F, _cubicBezierEasingFunction_0);
                // Frame 120.
                result.InsertKeyFrame(0.333333343F, 0F, _cubicBezierEasingFunction_0);
                // Frame 135.
                result.InsertKeyFrame(0.375F, 255F, _cubicBezierEasingFunction_0);
                // Frame 180.
                result.InsertKeyFrame(0.5F, 0F, _cubicBezierEasingFunction_0);
                // Frame 240.
                result.InsertKeyFrame(0.666666687F, 0F, _cubicBezierEasingFunction_0);
                // Frame 255.
                result.InsertKeyFrame(0.708333313F, 255F, _cubicBezierEasingFunction_0);
                // Frame 300.
                result.InsertKeyFrame(0.833333313F, 0F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_0_3()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _stepThenHoldEasingFunction);
                // Frame 40.
                result.InsertKeyFrame(0.111111112F, 0F, _holdThenStepEasingFunction);
                // Frame 55.
                result.InsertKeyFrame(0.152777776F, 255F, _cubicBezierEasingFunction_0);
                // Frame 100.
                result.InsertKeyFrame(0.277777791F, 0F, _cubicBezierEasingFunction_0);
                // Frame 160.
                result.InsertKeyFrame(0.444444448F, 0F, _cubicBezierEasingFunction_0);
                // Frame 175.
                result.InsertKeyFrame(0.486111104F, 255F, _cubicBezierEasingFunction_0);
                // Frame 220.
                result.InsertKeyFrame(0.611111104F, 0F, _cubicBezierEasingFunction_0);
                // Frame 280.
                result.InsertKeyFrame(0.777777791F, 0F, _cubicBezierEasingFunction_0);
                // Frame 295.
                result.InsertKeyFrame(0.819444418F, 255F, _cubicBezierEasingFunction_0);
                // Frame 340.
                result.InsertKeyFrame(0.944444418F, 0F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_113p332_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 113.332199F, _cubicBezierEasingFunction_0);
                // Frame 18.95.
                result.InsertKeyFrame(0.0526315793F, 0F, _cubicBezierEasingFunction_0);
                // Frame 75.79.
                result.InsertKeyFrame(0.210526317F, 0F, _cubicBezierEasingFunction_0);
                // Frame 90.
                result.InsertKeyFrame(0.25F, 255F, _cubicBezierEasingFunction_0);
                // Frame 132.63.
                result.InsertKeyFrame(0.368421048F, 0F, _cubicBezierEasingFunction_0);
                // Frame 189.47.
                result.InsertKeyFrame(0.526315808F, 0F, _cubicBezierEasingFunction_0);
                // Frame 203.68.
                result.InsertKeyFrame(0.565789461F, 255F, _cubicBezierEasingFunction_0);
                // Frame 246.32.
                result.InsertKeyFrame(0.684210539F, 0F, _cubicBezierEasingFunction_0);
                // Frame 303.16.
                result.InsertKeyFrame(0.842105269F, 0F, _cubicBezierEasingFunction_0);
                // Frame 317.37.
                result.InsertKeyFrame(0.881578922F, 255F, _cubicBezierEasingFunction_0);
                // Frame 340.11.
                result.InsertKeyFrame(0.944736838F, 119.000847F, _cubicBezierEasingFunction_0);
                // Frame 360.
                result.InsertKeyFrame(1F, 0F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_255_to_255()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 255F, _cubicBezierEasingFunction_0);
                // Frame 30.
                result.InsertKeyFrame(0.0833333358F, 255F, _cubicBezierEasingFunction_0);
                // Frame 40.
                result.InsertKeyFrame(0.111111112F, 0F, _cubicBezierEasingFunction_0);
                // Frame 100.
                result.InsertKeyFrame(0.277777791F, 0F, _cubicBezierEasingFunction_0);
                // Frame 110.
                result.InsertKeyFrame(0.305555552F, 255F, _cubicBezierEasingFunction_0);
                // Frame 210.
                result.InsertKeyFrame(0.583333313F, 255F, _cubicBezierEasingFunction_0);
                // Frame 220.
                result.InsertKeyFrame(0.611111104F, 0F, _cubicBezierEasingFunction_0);
                // Frame 280.
                result.InsertKeyFrame(0.777777791F, 0F, _cubicBezierEasingFunction_0);
                // Frame 290.
                result.InsertKeyFrame(0.805555582F, 255F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_360()
            {
                // Frame 0.
                var result = _rotationAngleInDegreesScalarAnimation_0_to_360 = CreateScalarKeyFrameAnimation(0F, 0F, _holdThenStepEasingFunction);
                // Frame 359.
                result.InsertKeyFrame(0.997222245F, 360F, _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_m360()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, _holdThenStepEasingFunction);
                // Frame 359.
                result.InsertKeyFrame(0.997222245F, -360F, _cubicBezierEasingFunction_0);
                return result;
            }

            ScalarKeyFrameAnimation t0ScalarAnimation_0_to_1()
            {
                // Frame 180.
                var result = CreateScalarKeyFrameAnimation(0.50000006F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                // Frame 359.
                result.InsertKeyFrame(0.997222185F, 1F, _cubicBezierEasingFunction_0);
                return result;
            }

            ScalarKeyFrameAnimation t1ScalarAnimation_0_to_1()
            {
                // Frame 323.1.
                var result = CreateScalarKeyFrameAnimation(0.897500038F, 0F, _stepThenHoldEasingFunction);
                result.SetReferenceParameter("_", _root);
                // Frame 360.
                result.InsertKeyFrame(0.99999994F, 1F, _cubicBezierEasingFunction_0);
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // dark-path
                shapes.Add(SpriteShape_0());
                // black-path
                shapes.Add(SpriteShape_1());
                // Path 2+Path 1
                shapes.Add(SpriteShape_2());
                // Path 2+Path 1
                shapes.Add(SpriteShape_3());
                // Path 2+Path 1
                shapes.Add(SpriteShape_4());
                // Path 1
                shapes.Add(SpriteShape_5());
                // Path 1
                shapes.Add(SpriteShape_6());
                // Path 1
                shapes.Add(SpriteShape_7());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // dark-path
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(247F, 256F), HoldThenStepEasingFunction());
                result.SetReferenceParameter("_", _root);
                // Frame 180.
                result.InsertKeyFrame(0.5F, new Vector2(265F, 256F), CubicBezierEasingFunction_0());
                // Frame 359.
                result.InsertExpressionKeyFrame(0.997222185F, "Pow(1-_.t0,3)*Vector2(265,256)+(3*Square(1-_.t0)*_.t0*Vector2(265,256))+(3*(1-_.t0)*Square(_.t0)*Vector2(250,256))+(Pow(_.t0,3)*Vector2(247,256))", StepThenHoldEasingFunction());
                // Frame 359.
                result.InsertKeyFrame(0.997222245F, new Vector2(247F, 256F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // black-path
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(238F, 256F), _holdThenStepEasingFunction);
                result.SetReferenceParameter("_", _root);
                // Frame 180.
                result.InsertKeyFrame(0.5F, new Vector2(274F, 256F), _cubicBezierEasingFunction_0);
                // Frame 359.
                result.InsertExpressionKeyFrame(0.997222185F, "Pow(1-_.t0,3)*Vector2(274,256)+(3*Square(1-_.t0)*_.t0*Vector2(274,256))+(3*(1-_.t0)*Square(_.t0)*Vector2(244,256))+(Pow(_.t0,3)*Vector2(238,256))", _stepThenHoldEasingFunction);
                // Frame 359.
                result.InsertKeyFrame(0.997222245F, new Vector2(238F, 256F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(256F, 224F), _holdThenStepEasingFunction);
                // Frame 120.
                result.InsertKeyFrame(0.333333343F, new Vector2(256F, 352F), _cubicBezierEasingFunction_0);
                // Frame 180.
                result.InsertKeyFrame(0.5F, new Vector2(256F, 224F), _cubicBezierEasingFunction_0);
                // Frame 300.
                result.InsertKeyFrame(0.833333313F, new Vector2(256F, 352F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(256F, 309.329987F), _holdThenStepEasingFunction);
                result.SetReferenceParameter("_", _root);
                // Frame 36.
                result.InsertKeyFrame(0.100000001F, new Vector2(256F, 352F), _cubicBezierEasingFunction_0);
                // Frame 90.
                result.InsertKeyFrame(0.25F, new Vector2(256F, 224F), _cubicBezierEasingFunction_0);
                // Frame 198.
                result.InsertKeyFrame(0.550000012F, new Vector2(256F, 352F), _cubicBezierEasingFunction_0);
                // Frame 252.
                result.InsertKeyFrame(0.699999988F, new Vector2(256F, 224F), _cubicBezierEasingFunction_0);
                // Frame 323.1.
                result.InsertKeyFrame(0.897499979F, new Vector2(256F, 308.264008F), _cubicBezierEasingFunction_0);
                // Frame 360.
                result.InsertExpressionKeyFrame(0.99999994F, "Pow(1-_.t1,3)*Vector2(256,308.264)+(3*Square(1-_.t1)*_.t1*Vector2(256,327.67))+(3*(1-_.t1)*Square(_.t1)*Vector2(256,244.756))+(Pow(_.t1,3)*Vector2(256,252))", _stepThenHoldEasingFunction);
                // Frame 360.
                result.InsertKeyFrame(1F, new Vector2(256F, 252F), _stepThenHoldEasingFunction);
                return result;
            }

            // - Layer aggregator
            // Path 2+Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_4()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(246F, 224F), _stepThenHoldEasingFunction);
                // Frame 50.
                result.InsertKeyFrame(0.138888896F, new Vector2(246F, 224F), _holdThenStepEasingFunction);
                // Frame 170.
                result.InsertKeyFrame(0.472222209F, new Vector2(246F, 352F), _cubicBezierEasingFunction_0);
                // Frame 230.
                result.InsertKeyFrame(0.638888896F, new Vector2(246F, 224F), _cubicBezierEasingFunction_0);
                // Frame 350.
                result.InsertKeyFrame(0.972222209F, new Vector2(246F, 352F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_5()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(200F, 330F), _holdThenStepEasingFunction);
                // Frame 15.
                result.InsertKeyFrame(0.0416666679F, new Vector2(200F, 330F), _cubicBezierEasingFunction_0);
                // Frame 60.
                result.InsertKeyFrame(0.166666672F, new Vector2(200F, 450F), _cubicBezierEasingFunction_0);
                // Frame 120.
                result.InsertKeyFrame(0.333333343F, new Vector2(200F, 330F), _cubicBezierEasingFunction_0);
                // Frame 135.
                result.InsertKeyFrame(0.375F, new Vector2(200F, 330F), _cubicBezierEasingFunction_0);
                // Frame 180.
                result.InsertKeyFrame(0.5F, new Vector2(200F, 450F), _cubicBezierEasingFunction_0);
                // Frame 240.
                result.InsertKeyFrame(0.666666687F, new Vector2(200F, 330F), _cubicBezierEasingFunction_0);
                // Frame 255.
                result.InsertKeyFrame(0.708333313F, new Vector2(200F, 330F), _cubicBezierEasingFunction_0);
                // Frame 300.
                result.InsertKeyFrame(0.833333313F, new Vector2(200F, 450F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_6()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(256F, 396.665985F), _holdThenStepEasingFunction);
                // Frame 18.95.
                result.InsertKeyFrame(0.0526315793F, new Vector2(256F, 450F), _cubicBezierEasingFunction_0);
                // Frame 75.79.
                result.InsertKeyFrame(0.210526317F, new Vector2(256F, 330F), _cubicBezierEasingFunction_0);
                // Frame 90.
                result.InsertKeyFrame(0.25F, new Vector2(256F, 330F), _cubicBezierEasingFunction_0);
                // Frame 132.63.
                result.InsertKeyFrame(0.368421048F, new Vector2(256F, 450F), _cubicBezierEasingFunction_0);
                // Frame 189.47.
                result.InsertKeyFrame(0.526315808F, new Vector2(256F, 330F), _cubicBezierEasingFunction_0);
                // Frame 203.68.
                result.InsertKeyFrame(0.565789461F, new Vector2(256F, 330F), _cubicBezierEasingFunction_0);
                // Frame 246.32.
                result.InsertKeyFrame(0.684210539F, new Vector2(256F, 450F), _cubicBezierEasingFunction_0);
                // Frame 303.16.
                result.InsertKeyFrame(0.842105269F, new Vector2(256F, 330F), _cubicBezierEasingFunction_0);
                // Frame 317.37.
                result.InsertKeyFrame(0.881578922F, new Vector2(256F, 330F), _cubicBezierEasingFunction_0);
                // Frame 340.11.
                result.InsertKeyFrame(0.944736838F, new Vector2(256F, 394F), _cubicBezierEasingFunction_0);
                // Frame 360.
                result.InsertKeyFrame(1F, new Vector2(256F, 450F), _cubicBezierEasingFunction_0);
                return result;
            }

            // - Layer aggregator
            // Path 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_7()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(312F, 330F), _stepThenHoldEasingFunction);
                // Frame 40.
                result.InsertKeyFrame(0.111111112F, new Vector2(312F, 330F), _holdThenStepEasingFunction);
                // Frame 55.
                result.InsertKeyFrame(0.152777776F, new Vector2(312F, 330F), _cubicBezierEasingFunction_0);
                // Frame 100.
                result.InsertKeyFrame(0.277777791F, new Vector2(312F, 450F), _cubicBezierEasingFunction_0);
                // Frame 160.
                result.InsertKeyFrame(0.444444448F, new Vector2(312F, 330F), _cubicBezierEasingFunction_0);
                // Frame 175.
                result.InsertKeyFrame(0.486111104F, new Vector2(312F, 330F), _cubicBezierEasingFunction_0);
                // Frame 220.
                result.InsertKeyFrame(0.611111104F, new Vector2(312F, 450F), _cubicBezierEasingFunction_0);
                // Frame 280.
                result.InsertKeyFrame(0.777777791F, new Vector2(312F, 330F), _cubicBezierEasingFunction_0);
                // Frame 295.
                result.InsertKeyFrame(0.819444418F, new Vector2(312F, 330F), _cubicBezierEasingFunction_0);
                // Frame 340.
                result.InsertKeyFrame(0.944444418F, new Vector2(312F, 450F), _cubicBezierEasingFunction_0);
                return result;
            }

            internal Extreme_sleet_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
